version: '3.9'
services:
  web:
    build: .
    container_name: toolcases-web
    env_file:
      - .env
    ports:
      - "5000:5000"
    volumes:
      - .:/app
      - ./app.db:/app/app.db
    command: python app.py 